version: '2'
services:
  meteor:
    image: fl/meteor:checklist
    labels:
      - traefik.backend=checklist
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:checklist.example.com
      - traefik.port=3000
    networks:
      - internal
      - proxy

networks:
  proxy:
    external: true
  internal:
    external: false